import { USERS_GENDERS, USERS_ROLES, USERS_STATUSES } from 'src/configs/database'
import { User } from 'src/models/user.entity'

export const USERS_SEEDER = [
  {
    // id: 1,
    username: 'Faridsh',
    email: 'farid.sh69@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 1,
    phone: '00989123423322',
    first_name: 'Farid',
    last_name: 'Shahidi',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 2,
    username: 'player2',
    email: 'player2@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 2,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '2',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 3,
    username: 'player3',
    email: 'player3@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 3,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '3',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 4,
    username: 'player4',
    email: 'player4@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 4,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '4',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 5,
    username: 'player5',
    email: 'player5@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 5,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '5',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 6,
    username: 'player6',
    email: 'player6@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 6,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '6',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 7,
    username: 'player7',
    email: 'player7@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 7,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '7',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 8,
    username: 'player8',
    email: 'player8@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 8,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '8',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
  {
    // id: 9,
    username: 'player9',
    email: 'player9@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 9,
    phone: '00989123423322',
    first_name: 'Player',
    last_name: '9',
    gender: USERS_GENDERS.male,
    password: 'Aa11',
  },
] as User[]
