import { User } from 'src/models/user.entity'
import { USERS_GENDERS, USERS_ROLES, USERS_STATUSES } from 'src/configs/database'

export const USERS_SEEDER = [
  {
    id: 1,
    username: 'sagtole',
    email: 'sag.tole@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 1,
    phone: '00989123423322',
    first_name: 'javad',
    last_name: 'hashemi',
    gender: USERS_GENDERS.male,
    password: '1',
  },
  {
    id: 2,
    username: 'alihasani',
    email: 'ali.hasani@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 2,
    phone: '00989123423322',
    first_name: 'ali',
    last_name: 'hasani',
    gender: USERS_GENDERS.male,
    password: '1',
  },
  {
    id: 3,
    username: 'test3',
    email: 't@3.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.player,
    avatar_id: 3,
    phone: '00989123423322',
    first_name: 't',
    last_name: '3',
    gender: USERS_GENDERS.male,
    password: '1',
  },
  {
    id: 4,
    username: 'test4',
    email: 't@4.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.player,
    avatar_id: 4,
    phone: '00989123423322',
    first_name: 't',
    last_name: '4',
    gender: USERS_GENDERS.male,
    password: '1',
  },
  {
    id: 5,
    username: 'test5',
    email: 't@5.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.player,
    avatar_id: 5,
    phone: '00989123423322',
    first_name: 't',
    last_name: '5',
    gender: USERS_GENDERS.male,
    password: '1',
  },
  {
    id: 6,
    username: 'test6',
    email: 't@6.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.player,
    avatar_id: 6,
    phone: '00989123423322',
    first_name: 't',
    last_name: '4',
    gender: USERS_GENDERS.male,
    password: '1',
  },
] as User[]
