import { USERS_GENDERS, USERS_ROLES, USERS_STATUSES } from 'src/configs/database'
import { User } from 'src/models/user.entity'

export const USERS_SEEDER = [
  {
    // id: 1,
    username: '1',
    email: 'player-1@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 1,
    phone: '00123456789',
    first_name: 'Farid',
    last_name: 'Shahidi',
    gender: USERS_GENDERS.male,
    password: '1',
  },
  {
    // id: 2,
    username: '2',
    email: 'player-2@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 2,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '2',
    gender: USERS_GENDERS.male,
    password: '2',
  },
  {
    // id: 3,
    username: '3',
    email: 'player-3@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 3,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '3',
    gender: USERS_GENDERS.male,
    password: '3',
  },
  {
    // id: 4,
    username: '4',
    email: 'player-4@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 4,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '4',
    gender: USERS_GENDERS.male,
    password: '4',
  },
  {
    // id: 5,
    username: '5',
    email: 'player-5@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 5,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '5',
    gender: USERS_GENDERS.male,
    password: '5',
  },
  {
    // id: 6,
    username: '6',
    email: 'player-6@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 6,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '6',
    gender: USERS_GENDERS.male,
    password: '6',
  },
  {
    // id: 7,
    username: '7',
    email: 'player-7@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 7,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '7',
    gender: USERS_GENDERS.male,
    password: '7',
  },
  {
    // id: 8,
    username: '8',
    email: 'player-8@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 8,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '8',
    gender: USERS_GENDERS.male,
    password: '8',
  },
  {
    // id: 9,
    username: '9',
    email: 'player-9@gmail.com',
    status: USERS_STATUSES.active,
    role: USERS_ROLES.admin,
    avatar_id: 9,
    phone: '00123456789',
    first_name: 'Player',
    last_name: '9',
    gender: USERS_GENDERS.male,
    password: '9',
  },
] as User[]
